apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Development-specific customization
patchesStrategicMerge:
  - patch-statefulset.yaml

# Add unique labels for the development overlay
commonLabels:
  environment: stage
