apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://YOUR_DATABASE_IP/keycloak-db
  KC_HOSTNAME: houseofllm.com
  KC_HEALTH_ENABLED: "true"
  KC_PROXY: edge
  JGROUPS_DNS_QUERY: keycloak
  PROXY_ADDRESS_FORWARDING: "true"
  KC_METRICS_ENABLED: "true"
  KC_HTTP_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: /auth
  KC_HOSTNAME_URL: https://houseofllm.com/keycloak/auth/
  JAVA_OPTS_APPEND: "-XX:+UseG1GC -XX:MaxRAMPercentage=80.0"
  KC_LOG_LEVEL: INFO