apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-statefulset.yaml
  - keycloak-service.yaml
  - keycloak-configmap.yaml
#  - keycloak-secrets.yaml
  - keycloak-service-account.yaml
  - ingress.yaml

# Specify any common labels
commonLabels:
  app: keycloak
